version: "3"
services:
  selenium-hub:
    image: selenium/hub
    container_name: selenium-hub
    ports:
    - "4444:4444"
  chrome:
    image: selenium/node-firefox-debug
    depends_on:
    - selenium-hub
    environment:
    - HUB_PORT_4444_TCP_ADDR=selenium-hub
    - HUB_PORT_4444_TCP_PORT=4444
    - NODE_MAX_INSTANCES=5
    - NODE_MAX_SESSION=5
  firefox:
    image: selenium/node-chrome-debug
    depends_on:
    - selenium-hub
    environment:
    - HUB_PORT_4444_TCP_ADDR=selenium-hub
    - HUB_PORT_4444_TCP_PORT=4444
    - NODE_MAX_INSTANCES=5
    - NODE_MAX_SESSION=5